name: Build

on:
  push:
    paths:
    - 'source/**'
    - 'data/**'
  pull_request:
    paths:
    - 'source/**'
    - 'data/**'


jobs:
  build:

    runs-on: macos-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, ubuntu-16.04, macos-latest]
    #   fail-fast: false
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Linux dependencies
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libpng-dev libjpeg-turbo8-dev libopenal-dev libmad0-dev libglew-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev scons
    - name: Install MacOS dependencies
      #if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install libmad libpng jpeg-turbo sdl2
    - name: compile
      run: |
        if [[ ${{ runner.os }} == 'Linux' ]]; then
          scons -j2;
          echo "::set-env name=ES_PATH::./endless-sky"
        elif [[ ${{ runner.os }} == 'macOS' ]]; then
          xcodebuild -configuration "Release" install;
          echo "::set-env name=ES_PATH::/tmp/EndlessSky.dst/Applications/Endless\ Sky.app/Contents/MacOS/Endless\ Sky"
          # echo "Completed macOS build";
          echo && ls -ghtr
        fi
    - name: Execute parse test
      run: |
        echo $ES_PATH
        echo "$ES_PATH"
        echo ${ES_PATH}
        echo "${ES_PATH}"
        ./tests/test_parse.sh "${ES_PATH}"
      env:
        ES_PATH: ${{ env.ES_PATH }}
